# Base configuration for GAN inversion
# Override specific settings in experiment configs or via CLI

# Paths
input_path: null  # Set via CLI
output_dir: "outputs"
weights_path: "hf://hajar001/stylegan2-ffhq-128"  # HuggingFace model

# Model settings
image_size: 128  # 128x128 for faster experimentation
latent_dim: 512
num_layers: 12  # For W+ space (128x128 model has 12 layers)

# Default inversion settings
latent_space: "W"  # W or W+
init_method: "mean_w"  # mean_w or random
loss_type: "l2"  # l2 or lpips

# Optimization
optimizer: "adam"
learning_rate: 0.01
steps: 300
betas: [0.9, 0.999]

# Device
device: "cuda"  # cuda or cpu

# Logging
log_interval: 50
save_intermediate: false

# Reproducibility
seed: 42
deterministic: true

# Output options
save_reconstructions: true
save_diffs: true
save_metrics: true
save_loss_curve: true

